20220621-1648

diff --git a/ansible/roles/cp4waiops-ai-manager-demo-content/tasks/25-post-ldap-register.yaml b/ansible/roles/cp4waiops-ai-manager-demo-content/tasks/25-post-ldap-register.yaml
--- a/ansible/roles/cp4waiops-ai-manager-demo-content/tasks/25-post-ldap-register.yaml
+++ b/ansible/roles/cp4waiops-ai-manager-demo-content/tasks/25-post-ldap-register.yaml
@@ -117,3 +117,111 @@
   #   ignore_errors: yes
   when: LDAPS.stdout_lines|length == 0
 
+
+
+
+
+
+- name: LDAPREGISTER -           📥 CREATE AI Manager Groups and Users
+  shell: |
+    set -x
+    
+    export WAIOPS_NAMESPACE=$(oc get po -A|grep aiops-orchestrator-controller |awk '{print$1}')
+    echo "       🛠️  Get Route"
+    export ROUTE=$(oc get route -n $WAIOPS_NAMESPACE cpd  -o jsonpath={.spec.host})          
+    echo "        Route: $ROUTE"
+    echo ""
+ 
+    echo "       🛠️  Getting ZEN Token"
+  
+    ZEN_API_HOST=$(oc get route -n $WAIOPS_NAMESPACE cpd -o jsonpath='{.spec.host}')
+    ZEN_LOGIN_URL="https://${ZEN_API_HOST}/v1/preauth/signin"
+    LOGIN_USER=admin
+    LOGIN_PASSWORD="$(oc get secret admin-user-details -n $WAIOPS_NAMESPACE -o jsonpath='{ .data.initial_admin_password }' | base64 --decode)"
+
+    ZEN_LOGIN_RESPONSE=$(
+    curl -k \
+    -H 'Content-Type: application/json' \
+    -XPOST \
+    "${ZEN_LOGIN_URL}" \
+    -d '{
+          "username": "'"${LOGIN_USER}"'",
+          "password": "'"${LOGIN_PASSWORD}"'"
+    }' 2> /dev/null
+    )
+
+    ZEN_LOGIN_MESSAGE=$(echo "${ZEN_LOGIN_RESPONSE}" | jq -r .message)
+
+    if [ "${ZEN_LOGIN_MESSAGE}" != "success" ]; then
+    echo "Login failed: ${ZEN_LOGIN_MESSAGE}" 1>&2
+
+    exit 2
+    fi
+
+    ZEN_TOKEN=$(echo "${ZEN_LOGIN_RESPONSE}" | jq -r .token)
+    echo "${ZEN_TOKEN}"
+
+    echo "Sucessfully logged in" 1>&2
+
+    echo ""
+
+
+    echo "***************************************************************************************************************************************************"
+    echo "   🛠️  Create Demo Group"
+    echo "     "	
+    export result=$(curl -X "POST" -k "https://$ROUTE/usermgmt/v2/groups" \
+      -H "Authorization: bearer $ZEN_TOKEN" \
+      -H 'Content-Type: application/json; charset=utf-8' \
+      -d '{
+      "account_id": 1000,
+            "name": "demo",
+      "description": "demo",
+      "role_identifiers": [
+        "zen_administrator_role"
+      ]
+    }')
+    echo "      🔎 Result: "
+    echo "       "$result|jq "._messageCode_" | sed 's/^/          /'
+    echo "     "	
+    echo "     "	
+
+    echo "***************************************************************************************************************************************************"
+    echo "   🛠️  Create Demo User"
+    echo "     "	
+    export result=$(curl -X "POST" -k "https://$ROUTE/usermgmt/v1/user" \
+      -H "Authorization: bearer $ZEN_TOKEN" \
+      -H 'Content-Type: application/json; charset=utf-8' \
+      -d '{
+    "username": "demo",
+    "user_roles": ["zen_administrator_role"],
+    "displayName": "demo",
+    "password": "P4ssw0rd!",
+    "email": "demo@ibm.com",
+    "approval_status": "approved",
+    "permissions": ["administrator"],
+     "misc": {
+        "dark_mode": true
+      }
+    }')
+    echo "      🔎 Result: "
+    echo "       "$result|jq "._messageCode_" | sed 's/^/          /'
+    echo "     "	
+    echo "     "	
+  register: output_string
+  ignore_errors: yes
+  args:
+    executable: /bin/bash
+    
+- name: TRAINING CREATE LAD -    ✅ RESULT
+  debug: 
+    var: output_string.stdout_lines
+  #when: PRINT_LOGINS == true
+
+
+
+
+
+
+
+
+
